server {
    listen 80;
    server_name tree.icamp.tech;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root  /var/www/tree.icamp.tech;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
